sudo: required
language: go
go:
  # - "1.16.x" At minimum the code should run make check on the latest two go versions in the default linux environment provided by Travis.
  - "1.16.x"

dist: xenial

services:
  - docker

matrix:
  include:
    - os: linux

before_install:
  - set -e
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    script: >-
      make configure &&
      make TAG=latest build &&
      make TAG=latest run &&
      make TAG=latest upload
    on:
      branch: main
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: >-
      make configure &&
      make TAG=testing build &&
      make TAG=testing run &&
      make TAG=testing upload
    on:
      tags: true
      condition: $TRAVIS_PULL_REQUEST = true

