name: release
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: setup environment
        run: |-
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: make configure
      - run: make TAG=latest build
      - run: make run
      - run: make upload
